import UIKit

// Generated by scripts/sync-design-tokens.rb from Config/DesignTokens.json.
// Do not edit; run `mise run tokens-sync` after token changes.
extension UIColor {
    struct Putio {
        struct Fg {
            static let destructiveForeground = UIColor(named: "putio.fg.destructive-foreground")!
            static let foreground = UIColor(named: "putio.fg.foreground")!
            static let foregroundMuted = UIColor(named: "putio.fg.foreground-muted")!
            static let invertForeground = UIColor(named: "putio.fg.invert-foreground")!
            static let primaryForeground = UIColor(named: "putio.fg.primary-foreground")!
            static let solidForeground = UIColor(named: "putio.fg.solid-foreground")!
            static let successForeground = UIColor(named: "putio.fg.success-foreground")!
        }

        struct Green {
            static let bg = UIColor(named: "putio.green.bg")!
            static let bgSecondary = UIColor(named: "putio.green.bg-secondary")!
            static let border = UIColor(named: "putio.green.border")!
            static let borderHover = UIColor(named: "putio.green.border-hover")!
            static let componentBg = UIColor(named: "putio.green.component-bg")!
            static let componentBgActive = UIColor(named: "putio.green.component-bg-active")!
            static let componentBgHover = UIColor(named: "putio.green.component-bg-hover")!
            static let line = UIColor(named: "putio.green.line")!
            static let solid = UIColor(named: "putio.green.solid")!
            static let solidHover = UIColor(named: "putio.green.solid-hover")!
            static let text = UIColor(named: "putio.green.text")!
            static let textSecondary = UIColor(named: "putio.green.text-secondary")!
        }

        struct Lime {
            static let step3 = UIColor(named: "putio.lime.3")!
        }

        struct Neutral {
            static let bg = UIColor(named: "putio.neutral.bg")!
            static let bgSecondary = UIColor(named: "putio.neutral.bg-secondary")!
            static let border = UIColor(named: "putio.neutral.border")!
            static let borderHover = UIColor(named: "putio.neutral.border-hover")!
            static let componentBg = UIColor(named: "putio.neutral.component-bg")!
            static let componentBgActive = UIColor(named: "putio.neutral.component-bg-active")!
            static let componentBgHover = UIColor(named: "putio.neutral.component-bg-hover")!
            static let line = UIColor(named: "putio.neutral.line")!
            static let solid = UIColor(named: "putio.neutral.solid")!
            static let solidHover = UIColor(named: "putio.neutral.solid-hover")!
            static let text = UIColor(named: "putio.neutral.text")!
            static let textSecondary = UIColor(named: "putio.neutral.text-secondary")!
        }

        struct Overlay {
            static let overlayFull = UIColor(named: "putio.overlay.overlay-full")!
            static let overlayInline = UIColor(named: "putio.overlay.overlay-inline")!
            static let shadowColor = UIColor(named: "putio.overlay.shadow-color")!
        }

        struct Red {
            static let bg = UIColor(named: "putio.red.bg")!
            static let bgSecondary = UIColor(named: "putio.red.bg-secondary")!
            static let border = UIColor(named: "putio.red.border")!
            static let borderHover = UIColor(named: "putio.red.border-hover")!
            static let componentBg = UIColor(named: "putio.red.component-bg")!
            static let componentBgActive = UIColor(named: "putio.red.component-bg-active")!
            static let componentBgHover = UIColor(named: "putio.red.component-bg-hover")!
            static let line = UIColor(named: "putio.red.line")!
            static let solid = UIColor(named: "putio.red.solid")!
            static let solidHover = UIColor(named: "putio.red.solid-hover")!
            static let text = UIColor(named: "putio.red.text")!
            static let textSecondary = UIColor(named: "putio.red.text-secondary")!
        }

        struct Surface {
            static let appBg = UIColor(named: "putio.surface.app-bg")!
            static let hiContrast = UIColor(named: "putio.surface.hi-contrast")!
            static let htmlBg = UIColor(named: "putio.surface.html-bg")!
            static let listItemBg = UIColor(named: "putio.surface.list-item-bg")!
            static let listItemBgActive = UIColor(named: "putio.surface.list-item-bg-active")!
            static let listItemBgHover = UIColor(named: "putio.surface.list-item-bg-hover")!
            static let listItemBorder = UIColor(named: "putio.surface.list-item-border")!
            static let loContrast = UIColor(named: "putio.surface.lo-contrast")!
            static let navBg = UIColor(named: "putio.surface.nav-bg")!
            static let navItemBg = UIColor(named: "putio.surface.nav-item-bg")!
            static let navItemBgActive = UIColor(named: "putio.surface.nav-item-bg-active")!
            static let navItemBgHover = UIColor(named: "putio.surface.nav-item-bg-hover")!
            static let segmentedControlBg = UIColor(named: "putio.surface.segmented-control-bg")!
            static let segmentedControlBgActive = UIColor(named: "putio.surface.segmented-control-bg-active")!
            static let transferListItemCompletingBg = UIColor(named: "putio.surface.transfer-list-item-completing-bg")!
            static let transferListItemDownloadingBg = UIColor(named: "putio.surface.transfer-list-item-downloading-bg")!
            static let transferListItemFinishedBg = UIColor(named: "putio.surface.transfer-list-item-finished-bg")!
            static let transferListItemPassiveBg = UIColor(named: "putio.surface.transfer-list-item-passive-bg")!
            static let transparent = UIColor(named: "putio.surface.transparent")!
        }

        struct Yellow {
            static let bg = UIColor(named: "putio.yellow.bg")!
            static let bgSecondary = UIColor(named: "putio.yellow.bg-secondary")!
            static let border = UIColor(named: "putio.yellow.border")!
            static let borderHover = UIColor(named: "putio.yellow.border-hover")!
            static let componentBg = UIColor(named: "putio.yellow.component-bg")!
            static let componentBgActive = UIColor(named: "putio.yellow.component-bg-active")!
            static let componentBgHover = UIColor(named: "putio.yellow.component-bg-hover")!
            static let line = UIColor(named: "putio.yellow.line")!
            static let solid = UIColor(named: "putio.yellow.solid")!
            static let solidHover = UIColor(named: "putio.yellow.solid-hover")!
            static let text = UIColor(named: "putio.yellow.text")!
            static let textSecondary = UIColor(named: "putio.yellow.text-secondary")!
        }

    }
}
