// GENERATED by scripts/sync-type-scale.rb from Config/TypeScale.json. Do not edit.
//
// The design system's Type · Scale on the two brand families — GT America
// (sans) and Berkeley Mono (numerics and code) — scaled through
// UIFontMetrics. Every accessor returns nil when the licensed faces are
// absent, so callers keep their original font.
import UIKit

enum BrandTypography {
    enum Role {
        case display
        case h1
        case h2
        case h3
        case h4
        case body
        case small
        case label
        case numeric
        case code
    }

    struct Style {
        let font: UIFont
        // Kerning in points at the resolved size (0 = none).
        let tracking: CGFloat
        let lineHeightMultiple: CGFloat
        let isUppercase: Bool
    }

    // Pass `traits` — a label's own trait collection — to keep tracking
    // and size in proportion at that content size category. Omit it to
    // resolve against the current environment.
    static func styleIfAvailable(_ role: Role, compatibleWith traits: UITraitCollection? = nil) -> Style? {
        switch role {
        case .display:
            return sans(.black, .largeTitle, tracking: -0.025, lineHeight: 0.92, uppercase: false, traits: traits)
        case .h1:
            return sans(.bold, .largeTitle, tracking: -0.02, lineHeight: 1.05, uppercase: false, traits: traits)
        case .h2:
            return sans(.bold, .title1, tracking: -0.015, lineHeight: 1.1, uppercase: false, traits: traits)
        case .h3:
            return sans(.medium, .title2, tracking: 0, lineHeight: 1.2, uppercase: false, traits: traits)
        case .h4:
            return sans(.medium, .title3, tracking: 0, lineHeight: 1.25, uppercase: false, traits: traits)
        case .body:
            return sans(.regular, .body, tracking: 0, lineHeight: 1.5, uppercase: false, traits: traits)
        case .small:
            return sans(.regular, .footnote, tracking: 0, lineHeight: 1.45, uppercase: false, traits: traits)
        case .label:
            return sans(.medium, .caption1, tracking: 0.08, lineHeight: 1.25, uppercase: true, traits: traits)
        case .numeric:
            return mono(.medium, .title3, tracking: 0, lineHeight: 1.2, uppercase: false, traits: traits)
        case .code:
            return mono(.regular, .footnote, tracking: 0, lineHeight: 1.45, uppercase: false, traits: traits)
        }
    }

    static func fontIfAvailable(_ role: Role) -> UIFont? {
        styleIfAvailable(role)?.font
    }

    private static func sans(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                             traits: UITraitCollection?) -> Style? {
        guard let brand = BrandFont.sansIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
        return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase, traits: traits)
    }

    private static func mono(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                             traits: UITraitCollection?) -> Style? {
        guard let brand = BrandFont.monoIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
        return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase, traits: traits)
    }

    // A role's base size is its anchor text style's native iOS size, which
    // is what lets UIFontMetrics scale it with the accessibility setting.
    private static func nativeSize(_ style: UIFont.TextStyle) -> CGFloat {
        UIFont.preferredFont(
            forTextStyle: style,
            compatibleWith: UITraitCollection(preferredContentSizeCategory: .large)
        ).pointSize
    }

    private static func make(_ brand: UIFont, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                             traits: UITraitCollection?) -> Style {
        let scaled = UIFontMetrics(forTextStyle: anchor).scaledFont(for: brand, compatibleWith: traits)
        return Style(
            font: scaled,
            // Tracking is em; scaling by the resolved point size gives an
            // absolute kern that holds its proportion at any size.
            tracking: tracking * scaled.pointSize,
            lineHeightMultiple: lineHeight,
            isUppercase: uppercase
        )
    }
}
