// GENERATED by scripts/sync-type-scale.rb from Config/TypeScale.json. Do not edit.
//
// The put.io design system's Type · Scale, resolved onto GT America (sans)
// and GT America Mono (mono) at each role's iOS base point and scaled for the
// current content size category via UIFontMetrics. Every accessor returns nil
// when the licensed faces are absent (verification builds), so callers fall
// back to their original font and snapshot baselines stay on system fonts.
import UIKit

enum BrandTypography {
    enum Role {
        case display
        case h1
        case h2
        case h3
        case h4
        case body
        case small
        case label
        case numeric
        case code
    }

    struct Style {
        let font: UIFont
        // Kerning in points at the resolved size (0 = none).
        let tracking: CGFloat
        let lineHeightMultiple: CGFloat
        let isUppercase: Bool
    }

    static func styleIfAvailable(_ role: Role) -> Style? {
        switch role {
        case .display:
            return sans(.black, .largeTitle, tracking: -0.025, lineHeight: 0.92, uppercase: false)
        case .h1:
            return sans(.bold, .largeTitle, tracking: -0.02, lineHeight: 1.05, uppercase: false)
        case .h2:
            return sans(.bold, .title1, tracking: -0.015, lineHeight: 1.1, uppercase: false)
        case .h3:
            return sans(.medium, .title2, tracking: 0, lineHeight: 1.2, uppercase: false)
        case .h4:
            return sans(.medium, .title3, tracking: 0, lineHeight: 1.25, uppercase: false)
        case .body:
            return sans(.regular, .body, tracking: 0, lineHeight: 1.5, uppercase: false)
        case .small:
            return sans(.regular, .footnote, tracking: 0, lineHeight: 1.45, uppercase: false)
        case .label:
            return sans(.medium, .caption1, tracking: 0.08, lineHeight: 1.25, uppercase: true)
        case .numeric:
            return mono(.medium, .title3, tracking: 0, lineHeight: 1.2, uppercase: false)
        case .code:
            return mono(.regular, .footnote, tracking: 0, lineHeight: 1.45, uppercase: false)
        }
    }

    static func fontIfAvailable(_ role: Role) -> UIFont? {
        styleIfAvailable(role)?.font
    }

    private static func sans(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool) -> Style? {
        guard let brand = BrandFont.sansIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
        return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase)
    }

    private static func mono(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool) -> Style? {
        guard let brand = BrandFont.monoIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
        return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase)
    }

    // Each role's base point size is the anchor text style's native iOS
    // size at the default content size category, so brand type matches
    // iOS norms and UIFontMetrics scales it with the accessibility setting.
    private static func nativeSize(_ style: UIFont.TextStyle) -> CGFloat {
        UIFont.preferredFont(
            forTextStyle: style,
            compatibleWith: UITraitCollection(preferredContentSizeCategory: .large)
        ).pointSize
    }

    private static func make(_ brand: UIFont, _ anchor: UIFont.TextStyle,
                             tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool) -> Style {
        let scaled = UIFontMetrics(forTextStyle: anchor).scaledFont(for: brand)
        return Style(
            font: scaled,
            tracking: tracking * scaled.pointSize,
            lineHeightMultiple: lineHeight,
            isUppercase: uppercase
        )
    }
}
