def fail($message): error($message);
def quote_wrapped:
  length >= 1 and
  ((startswith("\"") and endswith("\"")) or
   (startswith("'") and endswith("'")));
def control_character: any(explode[]; . < 32 or . == 127);
def safe_xcconfig_value: test("^[A-Za-z0-9._~:@/+?&=%-]+$");
def render_xcconfig: gsub("//"; "/$()/");
def render_optional: if . == "null" then "" else render_xcconfig end;

if type != "object" then
  fail("decrypted payload must be a JSON object")
elif keys != [
  "PUTIO_CHROMECAST_RECEIVER_APP_ID",
  "PUTIO_DEVELOPMENT_TEAM",
  "PUTIO_INTERCOM_API_KEY",
  "PUTIO_INTERCOM_APP_ID",
  "PUTIO_OAUTH_CLIENT_ID",
  "PUTIO_SENTRY_DSN"
] then
  fail("decrypted payload key inventory does not match the iOS config contract")
elif any(.[]; type != "string" or test("^\\s*$") or quote_wrapped or control_character) then
  fail("decrypted payload contains an empty, blank, non-string, quote-wrapped, or control-character value")
elif any(.[]; safe_xcconfig_value | not) then
  fail("decrypted payload contains xcconfig syntax that cannot be rendered safely")
elif (.PUTIO_DEVELOPMENT_TEAM | test("^[A-Z0-9]{10}$") | not) then
  fail("decrypted payload contains an invalid Apple development team identifier")
elif (.PUTIO_OAUTH_CLIENT_ID | test("^[0-9]+$") | not) then
  fail("decrypted payload contains an invalid OAuth client identifier")
elif (.PUTIO_CHROMECAST_RECEIVER_APP_ID | test("^[A-Z0-9]{8}$") | not) then
  fail("decrypted payload contains an invalid Chromecast receiver identifier")
elif (.PUTIO_INTERCOM_API_KEY | test("^(null|[A-Za-z0-9._:-]+)$") | not) then
  fail("decrypted payload contains an invalid Intercom API key")
elif (.PUTIO_INTERCOM_APP_ID | test("^(null|[A-Za-z0-9._:-]+)$") | not) then
  fail("decrypted payload contains an invalid Intercom app identifier")
elif (.PUTIO_SENTRY_DSN | test("^(null|https://[A-Za-z0-9._~%+:-]+@[A-Za-z0-9.:-]+/[A-Za-z0-9._~%+:/?&=-]+)$") | not) then
  fail("decrypted payload contains an invalid Sentry DSN")
else
  [
    "// Generated by scripts/secrets-setup.sh. Do not commit.",
    "",
    "PUTIO_DEVELOPMENT_TEAM = \(.PUTIO_DEVELOPMENT_TEAM | render_xcconfig)",
    "",
    "PUTIO_OAUTH_CLIENT_ID = \(.PUTIO_OAUTH_CLIENT_ID | render_xcconfig)",
    "PUTIO_CHROMECAST_RECEIVER_APP_ID = \(.PUTIO_CHROMECAST_RECEIVER_APP_ID | render_xcconfig)",
    "",
    "PUTIO_INTERCOM_API_KEY = \(.PUTIO_INTERCOM_API_KEY | render_optional)",
    "PUTIO_INTERCOM_APP_ID = \(.PUTIO_INTERCOM_APP_ID | render_optional)",
    "PUTIO_SENTRY_DSN = \(.PUTIO_SENTRY_DSN | render_optional)"
  ]
  | join("\n")
end
