#!/bin/bash

set -euo pipefail

output="${SECRETS_OUTPUT:-Config/Local.xcconfig}"
infisical_domain="${INFISICAL_API_URL:-https://eu.infisical.com/api}"
infisical_project_id="${INFISICAL_PROJECT_ID:-b2fcfbd7-19e0-4b87-a797-93d125c432ce}"
infisical_env="${INFISICAL_ENV:-dev}"
infisical_path="${INFISICAL_PATH:-/ios}"

if ! command -v infisical >/dev/null 2>&1; then
  echo "Infisical CLI is required. Install it with: brew install infisical" >&2
  exit 1
fi

tmp_env="$(mktemp)"
cleanup() {
  rm -f "$tmp_env"
}
trap cleanup EXIT

infisical export \
  --silent \
  --domain "$infisical_domain" \
  --projectId "$infisical_project_id" \
  --env "$infisical_env" \
  --path "$infisical_path" \
  --format dotenv \
  --output-file "$tmp_env"

set -a
# shellcheck disable=SC1090
. "$tmp_env"
set +a

missing=()
for name in PUTIO_DEVELOPMENT_TEAM PUTIO_OAUTH_CLIENT_ID PUTIO_CHROMECAST_RECEIVER_APP_ID; do
  if [[ -z "${!name:-}" ]]; then
    missing+=("$name")
  fi
done

if (( ${#missing[@]} > 0 )); then
  printf 'Missing required Infisical values in %s: %s\n' "$infisical_path" "${missing[*]}" >&2
  exit 1
fi

mkdir -p "$(dirname "$output")"

{
  echo "// Generated by scripts/secrets-setup.sh. Do not commit."
  echo
  printf 'PUTIO_DEVELOPMENT_TEAM = %s\n' "${PUTIO_DEVELOPMENT_TEAM:-}"
  echo
  printf 'PUTIO_OAUTH_CLIENT_ID = %s\n' "${PUTIO_OAUTH_CLIENT_ID:-}"
  printf 'PUTIO_CHROMECAST_RECEIVER_APP_ID = %s\n' "${PUTIO_CHROMECAST_RECEIVER_APP_ID:-}"
  echo
  printf 'PUTIO_INTERCOM_API_KEY = %s\n' "${PUTIO_INTERCOM_API_KEY:-}"
  printf 'PUTIO_INTERCOM_APP_ID = %s\n' "${PUTIO_INTERCOM_APP_ID:-}"
  printf 'PUTIO_SENTRY_DSN = %s\n' "${PUTIO_SENTRY_DSN:-}"
} > "$output"

chmod 600 "$output"

echo "Wrote $output"
