#!/usr/bin/env ruby

# Generates the BrandTypography Swift API from the vendored design-system type
# scale. Mirrors the color-token and Phosphor-icon sync pattern:
#
#   ruby scripts/sync-type-scale.rb           # regenerate BrandTypography.swift
#   ruby scripts/sync-type-scale.rb --check   # fail on drift (verify gate)
#
# Source: Config/TypeScale.json — a generated mirror of the design system's
# Type · Scale. Do not hand-edit values there or the output here.

require "json"

class TypeScaleSync
  ROOT = File.expand_path("..", __dir__)
  TOKENS_PATH = File.join(ROOT, "Config", "TypeScale.json")
  SWIFT_PATH = File.join(ROOT, "Putio", "Common", "BrandTypography.swift")

  WEIGHTS = { "regular" => ".regular", "medium" => ".medium", "bold" => ".bold", "black" => ".black" }.freeze
  ANCHORS = %w[largeTitle title1 title2 title3 headline body callout subheadline footnote caption1 caption2].freeze

  def initialize(check_only:)
    @check_only = check_only
    @roles = JSON.parse(File.read(TOKENS_PATH)).fetch("roles")
  end

  def run
    swift = render_swift
    if @check_only
      # Compare bytes, not strings: the generated Swift contains non-ASCII
      # characters, and under a POSIX/C locale File.read would return a
      # differently-encoded string and falsely report drift.
      current = File.exist?(SWIFT_PATH) ? File.binread(SWIFT_PATH) : "".b
      if current != swift.b
        warn "BrandTypography.swift is out of sync with Config/TypeScale.json. Run: make type-scale-sync"
        exit 1
      end
      puts "Verified #{@roles.size} type-scale roles."
    else
      File.write(SWIFT_PATH, swift)
      puts "Generated BrandTypography.swift (#{@roles.size} roles)."
    end
  end

  private

  def render_swift
    cases = @roles.map { |r| "        case #{r.fetch("name")}" }.join("\n")
    resolvers = @roles.map { |role| render_case(role) }.join("\n")

    <<~SWIFT
      // GENERATED by scripts/sync-type-scale.rb from Config/TypeScale.json. Do not edit.
      //
      // The put.io design system's Type · Scale, resolved onto the two brand
      // families — GT America (sans) and Berkeley Mono (mono: numerics and code)
      // — at each role's iOS base point and scaled for the current content size
      // category via UIFontMetrics. Every accessor returns nil when the licensed
      // faces are absent (verification builds), so callers fall back to their
      // original font and snapshot baselines stay on system fonts.
      import UIKit

      enum BrandTypography {
          enum Role {
      #{cases}
          }

          struct Style {
              let font: UIFont
              // Kerning in points at the resolved size (0 = none).
              let tracking: CGFloat
              let lineHeightMultiple: CGFloat
              let isUppercase: Bool
          }

          // Pass `traits` to resolve a role against a specific content size
          // category (e.g. a label's own trait collection) so tracking and size
          // stay in proportion; omit it (nil) to resolve for the current
          // environment, which is what the font-only call sites use.
          static func styleIfAvailable(_ role: Role, compatibleWith traits: UITraitCollection? = nil) -> Style? {
              switch role {
      #{resolvers}
              }
          }

          static func fontIfAvailable(_ role: Role) -> UIFont? {
              styleIfAvailable(role)?.font
          }

          private static func sans(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                                   tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                                   traits: UITraitCollection?) -> Style? {
              guard let brand = BrandFont.sansIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
              return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase, traits: traits)
          }

          private static func mono(_ weight: UIFont.Weight, _ anchor: UIFont.TextStyle,
                                   tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                                   traits: UITraitCollection?) -> Style? {
              guard let brand = BrandFont.monoIfAvailable(size: nativeSize(anchor), weight: weight) else { return nil }
              return make(brand, anchor, tracking: tracking, lineHeight: lineHeight, uppercase: uppercase, traits: traits)
          }

          // Each role's base point size is the anchor text style's native iOS
          // size at the default content size category, so brand type matches
          // iOS norms and UIFontMetrics scales it with the accessibility setting.
          private static func nativeSize(_ style: UIFont.TextStyle) -> CGFloat {
              UIFont.preferredFont(
                  forTextStyle: style,
                  compatibleWith: UITraitCollection(preferredContentSizeCategory: .large)
              ).pointSize
          }

          private static func make(_ brand: UIFont, _ anchor: UIFont.TextStyle,
                                   tracking: CGFloat, lineHeight: CGFloat, uppercase: Bool,
                                   traits: UITraitCollection?) -> Style {
              let scaled = UIFontMetrics(forTextStyle: anchor).scaledFont(for: brand, compatibleWith: traits)
              return Style(
                  font: scaled,
                  // tracking is em; multiplying by the trait-scaled point size
                  // yields an absolute kern that stays in proportion at any size.
                  tracking: tracking * scaled.pointSize,
                  lineHeightMultiple: lineHeight,
                  isUppercase: uppercase
              )
          }
      }
    SWIFT
  end

  def render_case(role)
    name = role.fetch("name")
    family = role.fetch("family")
    raise "unknown family #{family}" unless %w[sans mono].include?(family)

    weight = WEIGHTS.fetch(role.fetch("weight"))
    anchor = role.fetch("anchor")
    raise "unknown anchor #{anchor}" unless ANCHORS.include?(anchor)

    line = format_number(role.fetch("lineHeight"))
    track = format_number(role.fetch("tracking"))
    upper = role.fetch("uppercase") ? "true" : "false"

    "        case .#{name}:\n" \
      "            return #{family}(#{weight}, .#{anchor}, tracking: #{track}, lineHeight: #{line}, uppercase: #{upper}, traits: traits)"
  end

  def format_number(value)
    # Emit integers without a trailing .0 so the generated Swift reads cleanly.
    value == value.to_i ? value.to_i.to_s : value.to_s
  end
end

TypeScaleSync.new(check_only: ARGV.include?("--check")).run
